repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.8"
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    - id: isort
      name: isort
      entry: isort
      require_serial: true
      language: python
      types:
      - python

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: ".*(.fits|.fts|.fit|.txt|.pro|.asdf)"
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
        args: [ '--enforce-all','--maxkb=1000' ]
      - id: end-of-file-fixer
        exclude: ".*(.fits|.fts|.fit|.txt|.pro|.asdf|.bib|tca.*)"
      - id: mixed-line-ending
        exclude: ".*(.fits|.fts|.fit|.txt|.bib|.asdf|tca.*)"

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
        - tomli
