# version with the image normalized to look like the spectra

[paths]
response = "data/response_img_normalized.fits"
weights = "data/forwardmodel_img_normalized.fits"
image = "data/weights_img_normalized.fits"
output = "output/"

[settings]
solution_fov_width = 2
detector_row_range = [450, 455]
field_angle_range = [-2160, 2160]
response_dependency_name = "logt"
response_dependency_list =[5.7, 5.8, 5.9,
    6.0 , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9,
    7.0 , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7]
smooth_over = 'dependence'
alphas = [5]
rhos = [0.1]

# Inversion Time = 13.962096929550171
