[paths]
response = "data/response_img_normalized.fits"
weights = "data/weights_img_normalized.fits"
image = "data/forwardmodel_img_normalized.fits"
output = "output/img_norm/"

[settings]
solution_fov_width = 2
detector_row_range = [450, 900]
field_angle_range = [-2160, 2160]
response_dependency_name = "logt"
response_dependency_list =[5.7, 5.8, 5.9,
    6.0 , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9,
    7.0 , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7]
smooth_over = 'dependence'
alphas = [6.02]
rhos = [1.0]

# Inversion Time = 123.58615684509277 # threaded execution
# Inversion Time = 332.0509181022644  # default number of processes in process pool
# Inversion Time = 440.9607219696045  # 4 processes in process pool (seems to go around 80% CPU with some fluctuation)
#### LIMIT NUMPY TO 1 THREAD
# Inversion Time = 263.8916232585907  # 4 processes with numpy limited to 1 thread
# Inversion Time = 81.74327301979065  # threaded execution with numpy limited to 1 thread
# Inversion Time = 148.79005193710327 # 11 processes with numpy limited to 1 thread (should match the threaded number of threads)
# Inversion Time = 152.01935005187988 # same as above with a thread pool
# Inversion Time = 147.7941930294037  # my thread pool executor with inits with 11 max workers
# Inversion Time = 144.82306694984436 # my process pool executor with inits with 11 max workers
# Inversion Time = 145.85570001602173 # same as above with max_iter decreased by factor of 10
# Inversion Time = 75.56018900871277  # my no shared memory thread pool executor with 11 max workers
# Inversion Time = 77.73930597305298  # my process pool executor with copy on write for global with 11 max workers
# Inversion Time = 88.20389604568481  # same as above with numpy having 2 threads
# Inversion Time = 42.56954908370972  # same as above wtih numpy having 1 thread and selection='cyclic'

# changing alpha can dramatically slow things
# set alpha = 0.1 then Inversion Time = 1208.5097889900208
# set alpha = 0.1 and selection = 'cyclic' Inversion Time = 464.01495003700256

# warm start test
# 50 rows:
# off = Inversion Time = 25.761871099472046
# on  = Inversion Time = 22.579617023468018
