# chop of the image to see the results of the spectra only
[paths]
response = "data/response_only_spectra.fits"
weights = "data/weights_only_spectra.fits"
image = "data/forward_model_only_spectra.fits"
output = "output/only_spectra/"

[settings]
solution_fov_width = 2
detector_row_range = [450, 900]
field_angle_range = [-2160, 2160]
response_dependency_name = "logt"
response_dependency_list =[5.7, 5.8, 5.9,
    6.0 , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9,
    7.0 , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7]
smooth_over = 'dependence'
alphas = [1.01] #[5]
rhos = [0.501] #[0.1]

# 68 seconds
